eureka:
  client:
    serviceUrl:
      #Only one server    
      #defaultZone: http://localhost:8010/eureka/
      #Several servers
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
      
words: ran,knew,had,saw,bought

server:
  # (this will cause a random, unused port to be assigned if none is specified)
  port: ${PORT:${SERVER_PORT:0}}