eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
      
words: a,the

server:
  # (this will cause a random, unused port to be assigned if none is specified)
  port: ${PORT:${SERVER_PORT:0}}